title: The AI Circuit
description: News and analysis on semiconductors, AI hardware, and the future of compute
theme: jekyll-theme-primer

# Blog settings
permalink: /:year/:month/:day/:title/
markdown: kramdown

# GitHub Pages settings
github:
  is_project_page: true
  repository_url: https://github.com/hankthevc/Blog-Tool

# AI Blog Tool config
openai_api_key: "${OPENAI_API_KEY}"
mixtral_model_path: "/local/path/to/mixtral/model"
niche_detection_frequency_days: 7
content_generation_frequency_days: 1
analytics_provider: "plausible"
adsense_id: "your_google_adsense_id"
amazon_affiliate_tag: "your_affiliate_tag"
notification_channel: "email"
notification_api_key: "your_notification_api_key"
auto_revision_interval_days: 30
backup_frequency_days: 7
blog:
  title: "The AI Circuit"
  author: "AI Ghostwriter"
  output_dir: "posts"
  deploy_branch: "gh-pages"
  repo_url: "https://github.com/hankthevc/Blog-Tool"